### ISSUE TITLE
Saving macro fails with NameError: name 'fnSuffix' is not defined

### ISSUE THREAD

**Issue by fatherofinvention** [saulpw/visidata#1280]
**Small description**
When saving a recorded macro error **_NameError: name 'fnSuffix' is not defined_** is printed to the screen no matter what is entered as a keystroke. I have tried single characters, numbers, and strings, including keyboard modifiers and omiting them, but none of those combinations work.

**Actual result with screenshot**
<img width="1227" alt="CleanShot 2022-02-03 at 09 17 48@2x" src="https://user-images.githubusercontent.com/24985048/152371511-36d08cb0-216d-43cc-829e-28a2a56753e0.png">

`Traceback (most recent call last):
  File "/opt/homebrew/Cellar/visidata/2.8/libexec/lib/python3.9/site-packages/visidata/basesheet.py", line 167, in execCommand
    escaped = super().execCommand2(cmd, vdglobals=vdglobals)
  File "/opt/homebrew/Cellar/visidata/2.8/libexec/lib/python3.9/site-packages/visidata/basesheet.py", line 69, in execCommand2
    exec(code, vdglobals, LazyChainMap(vd, self))
  File "macro-record", line 1, in <module>
    import plugins.dedupe
  File "/opt/homebrew/Cellar/visidata/2.8/libexec/lib/python3.9/site-packages/visidata/macros.py", line 60, in startMacro
    vd.cmdlog.saveMacro(vd.macroMode.rows, ks)
  File "/opt/homebrew/Cellar/visidata/2.8/libexec/lib/python3.9/site-packages/visidata/macros.py", line 39, in saveMacro
    macropath = Path(fnSuffix(options.visidata_dir+"macro"))
NameError: name 'fnSuffix' is not defined
`

**Steps to reproduce with sample data and a .vd**

1. Record macro
2. Enter anything into keystroke input
3. Get error

**Additional context**
Visidata version: 2.8
MacOS version: 12.2
Python version: 3.9.10

**Comment by anjakefala** [comment]
Thanks for the bug report @fatherofinvention! =) Should be fixed, now.

**Comment by code86** [comment]
I am still getting the same error message as OP. 

Ctrl+E (error-recent) shows error was activated in line 39 of macros.py

In macros.py ([line 39](https://github.com/saulpw/visidata/blob/stable/visidata/macros.py)), `fnSuffix` is called with one argument.

But in cmdlog.py ([line 42](https://github.com/saulpw/visidata/blob/stable/visidata/cmdlog.py)), `fnSuffix` is defined with two parameters? (vd, prefix)

Could that be the problem?

---
  File "/Users/code86/opt/miniconda3/envs/env2/lib/python3.8/site-packages/visidata/macros.py", line 39, in saveMacro
    macropath = Path(fnSuffix(options.visidata_dir+"macro"))
NameError: name 'fnSuffix' is not defined

**Comment by anjakefala** [comment]
Hi @code86!

I should have been clearer in the message. 

This bug was fixed on the `develop` branch of VisiData. We have not released a newer version of VisiData since it was fixed.

I am not sure how to use `conda` to install a package through a git branch, but the way to do it with pip is `pip3 install --upgrade git+https://github.com/saulpw/visidata.git@develop`. 
(**Edit**: I checked, and the stackoverflow accepted way is to use pip as described https://stackoverflow.com/questions/19042389/conda-installing-upgrading-directly-from-github)


****

Some additional technical info:

> In macros.py ([line 39](https://github.com/saulpw/visidata/blob/stable/visidata/macros.py)), fnSuffix is called with one argument.
> But in cmdlog.py ([line 42](https://github.com/saulpw/visidata/blob/stable/visidata/cmdlog.py)), fnSuffix is defined with two parameters? (vd, prefix)

Yup! That was the problem. [Execstrings](https://www.visidata.org/docs/api/commands#command-context) in VisiData (`addCommand('keystroke', 'longname', 'execstr')`) do not require `vd.` or `sheet.`prefixes. They will look up symbols in the current `sheet` and in `vd` obj before they look for it in the global namespace of the `visidata` module. `sheet.` and `vd.` are required outside of execstrings, as you noticed, and were forgotten in that location. Hence the bug.

**Comment by fscheong** [comment]
Thank you, @anjakefala!
