### ISSUE TITLE
[vdsql] pip installs incompatible legacy version

### ISSUE THREAD

**Issue by ned2** [saulpw/visidata#2080]
**Small description**
I loaded up a DuckDB database fine, and then hit `F` to create a frequency table and got:

    AttributeError: 'Table' object has no attribute 'get_column'

Looks like it might be because Ibis removed `ibis.expr.types.Table.get_column()` back in v5.0.0?
https://github.com/ibis-project/ibis/releases/tag/5.0.0

*Steps to reproduce*

Given a DuckDB database `duck.duckdb` created like this with Python

```python
import duckdb

with duckdb.connect("duck.duckdb") as conn:
    conn.sql("CREATE TABLE test as SELECT 'hello' as hello, unnest(range(10)) as values")
```

Then opening the database with vdsql like this:
    
    vdsql duck.duckdb

Open the `test` table, and then press `F` on any column.

*Traceback*
```
 Traceback (most recent call last):                                                                                                      ║                                                     
   File "/home/ned/.pyenv/versions/3.11.6/envs/book/lib/python3.11/site-packages/vdsql/ibis.py", line 256, in get_ibis_col               ║                                                     
     r = query.get_column(col.ibis_name)                                                                                                 ║                                                     
         ^^^^^^^^^^^^^^^^                                                                                                                ║                                                     
   File "/home/ned/.pyenv/versions/3.11.6/envs/book/lib/python3.11/site-packages/ibis/expr/types/relations.py", line 646, in __getattr__ ║                                                     
     raise AttributeError(f"'Table' object has no attribute {key!r}")                                                                    ║                                                     
 AttributeError: 'Table' object has no attribute 'get_column'                                                                            ║                                                     
                                                                                                                                         ║                                                     
 During handling of the above exception, another exception occurred:                                                                     ║                                                     
                                                                                                                                         ║                                                     
 Traceback (most recent call last):                                                                                                      ║                                                     
   File "/home/ned/.pyenv/versions/3.11.6/envs/book/lib/python3.11/site-packages/visidata/basesheet.py", line 187, in execCommand        ║                                                     
     escaped = super().execCommand2(cmd, vdglobals=vdglobals)                                                                            ║                                                     
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                            ║                                                     
   File "/home/ned/.pyenv/versions/3.11.6/envs/book/lib/python3.11/site-packages/visidata/basesheet.py", line 74, in execCommand2        ║                                                     
     exec(code, vdglobals, LazyChainMap(vd, self))                                                                                       ║                                                     
   File "freq-col", line 1, in <module>                                                                                                  ║                                                     
   File "/home/ned/.pyenv/versions/3.11.6/envs/book/lib/python3.11/site-packages/vdsql/ibis.py", line 187, in groupBy                    ║                                                     
     aggr_cols = [c.ibis_col.count() for c in groupByCols]                                                                               ║                                                     
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                               ║                                                     
   File "/home/ned/.pyenv/versions/3.11.6/envs/book/lib/python3.11/site-packages/vdsql/ibis.py", line 187, in <listcomp>                 ║                                                     
     aggr_cols = [c.ibis_col.count() for c in groupByCols]                                                                               ║                                                     
                  ^^^^^^^^^^                                                                                                             ║                                                     
   File "/home/ned/.pyenv/versions/3.11.6/envs/book/lib/python3.11/site-packages/visidata/extensible.py", line 90, in dofunc             ║                                                     
     return func(self)                                                                                                                   ║                                                     
            ^^^^^^^^^^                                                                                                                   ║                                                     
   File "/home/ned/.pyenv/versions/3.11.6/envs/book/lib/python3.11/site-packages/vdsql/ibis.py", line 243, in ibis_col                   ║                                                     
     return col.get_ibis_col(col.sheet.query)                                                                                            ║                                                     
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                            ║                                                     
   File "/home/ned/.pyenv/versions/3.11.6/envs/book/lib/python3.11/site-packages/vdsql/ibis.py", line 258, in get_ibis_col               ║                                                     
     r = query.get_column(col.name)                                                                                                      ║                                                     
         ^^^^^^^^^^^^^^^^                                                                                                                ║                                                     
   File "/home/ned/.pyenv/versions/3.11.6/envs/book/lib/python3.11/site-packages/ibis/expr/types/relations.py", line 646, in __getattr__ ║                                                     
     raise AttributeError(f"'Table' object has no attribute {key!r}")                                                                    ║                                                     
 AttributeError: 'Table' object has no attribute 'get_column'                             
```

**Additional context**
Visidata version: 2.11.1
Python version: 3.11.6
Ibis version: 7.0.0
DuckDB version: 0.9.1

**Comment by saulpw** [comment]
Thanks for filing this issue, @ned2.  I believe this is fixed in develop (or at least I was using the freq table with Clickhouse over the weekend).  Could you verify this is the case?  We're aiming to release VisiData 3.0 along with the next version of vdsql in a month or two.

**Comment by ned2** [comment]
Heya @saulpw, I just tried it with the `latest` develop branch and I'm unfortunately still seeing the issue.

**Comment by ned2** [comment]
Ahhhh I see what's happened. It looks like the `vdsql` package on PyPI is resolving to the old repo before it was merged into this monorepo. So while I was indeed running the latest Visidata, the vdsql command was invoking the rather old `vdsql-0.1.1`

To install I followed the instructions on the [vdsql announcement blog post](https://www.visidata.org/blog/2022/connect-visidata-to-sql-databases-with-vdsql/) of:

    pip install vdsql

I thought maybe these instructions might have been superseded with the incorporation into the monorepo. But the [vdsql readme](https://github.com/saulpw/visidata/tree/develop/visidata/apps/vdsql) still has the same instructions.

I was able to install the actual latest vdsql through the alternate git-clone instructions (and then everything works fine), but perhaps that's now the only way to get the correct version installed?

**Comment by ned2** [comment]
One other thing I noticed when installing vdsql from the GitHub repo is that Pandas is constrained to `pandas<2.0,>=1.5.0` which is a bit limiting when installing into environments for doing data stuff, given that Pandas is now at version 2.1.1.

@saulpw would it make sense to close this issue and create a new one specifically around installing the `vdsql` package with pip installing a legacy version?

**Comment by saulpw** [comment]
Yes, currently the only way to install the unreleased version is via the git-clone instructions.  We'll release a new vdsql in PyPI alongside VisiData 3.0.  (Actually we may release vdsql with the visidata package, and make the vdsql package in PyPI just include more dependencies.)

I'll change the subject on this issue to reflect the actual problem, and I don't think we need a new issue to track vdsql--we definitely know about it already and won't forget.  Unless you think there's something else we need to do before then to prevent other people from being confused?  If so, I'd appreciate a PR updating whichever docs you read, to make things clearer to people who come along like you and want things to work before the release.

**Comment by saulpw** [comment]
As for Pandas, we can probably relax the version constraint; I added `<2.0` because apparently PySpark has issues with it.  But if everything else for vdsql and VisiData works fine with the latest Pandas then let's remove that restriction, and people can moderate their own Pandas versions.

**Comment by ned2** [comment]
ah cool, great you're already across that then @saulpw. 

I do think it would be good to do something now to reduce confusion, but I'm not sure what the best thing would be. currently, anyone who hears about vdsql and follows the instructions in [this blog post](https://www.visidata.org/blog/2022/connect-visidata-to-sql-databases-with-vdsql) (which is what I did, and I suspect is probably the most discoverable vdsql resource) will run `pip install vdsql`, which will get them the old archived version currently on PyPI. Then they'll likely have similar challenges to the one I had or maybe other kinds of unexpected things happening.

If updating that blog post with some kind of appropriate note is an option, I feel like that would go a decent way to mitigating the problem.

**Comment by anjakefala** [comment]
Blogpost has been updated with the current instructions! Thanks for drawing our attention to it. =)
