### ISSUE TITLE
[v2.-4] Sqlite InterfaceError when saving Nones

### ISSUE THREAD

**Issue by jtf621** [saulpw/visidata#570]
When I open a sqlite file and try to save-all `g^S` as a new sqlite file, I get an `sqlite3.InterfaceError: Error binding parameter 3 - probably unsupported type.`

I am testing the current HEAD of the develop branch (f5513187098ad1068ee5096f2d77d0024cc4d2db). 

**Expected result**
An unchanged copy of the original file saved with the new name.

**Actual result with screenshot**

![image](https://user-images.githubusercontent.com/2312781/82694707-be676880-9c31-11ea-8899-65b00466bfe7.png)

**Steps to reproduce with sample data and a .vd**

Make a local copy of the visidata/sample_data/employees.sqlite file and run
```
sheet	col	row	longname	input	keystrokes	comment
	SqliteSheet	header	set-option	0		
	UsvSheet	delimiter	set-option	␞		
	UsvSheet	row_delimiter	set-option	␟		
			open-file	employees.sqlite	o	
employees		キemployees.dept	dive-row		^J	open sheet with copies of rows referenced in current row
employees		キemployees.emp	dive-row		^J	open sheet with copies of rows referenced in current row
employees.emp			save-all	new.sqlite	g^S	save all sheets to given file or directory)
```

**Comment by anjakefala** [comment]
@jtf621, so far that seems to be an issue with employees.emp specifically. employees.dept saves fine. I am trying to narrow it down.

**Comment by anjakefala** [comment]
(There is a bug with save-all as well, but it is distinct from this one.)

**Comment by anjakefala** [comment]
The bug related to this interface error is because that table contains cells that are treated as `None`s in VisiData. 

```
sqlvals.append(col.getTypedValue(r))
sql = 'INSERT INTO "%s" VALUES (%s)' % (tblname, ','.join('?' for v in sqlvals))
```

and then when I follow into `getTypedValue()`
```
if val is None:  # None values propagate to TypedWrappers                                                                                                                                                    
    return TypedWrapper(func, None)  
```

So this error, for now, is going to pop up whenever we are inserting an sqlite row with `None`s in it.

**Comment by anjakefala** [comment]
This should be fixed now!

We can refactor this better at a later time. This seems like a module that will likely be useful in other places.

**Comment by jtf621** [comment]
@anjakefala I still get an error, but the message has changed.

![image](https://user-images.githubusercontent.com/2312781/83180021-cd965c80-a0f0-11ea-89f7-3f5efa96ffb9.png)

testing version 70e837dbca12f4df56485a7a5da0a0483e78439b

**Comment by anjakefala** [comment]
@jtf621 I cannot reproduce, I am sorry! If you could play with it, and help me debug the problem, that would be wonderful. Otherwise, I am going to keep this issue closed.

`Ctrl+E` reveals more information the stacktrace. The code for sqlite saving is in `visidata/loaders/sqlite.py`.

**Comment by jtf621** [comment]
@anjakefala I would be happy to help debug.

![image](https://user-images.githubusercontent.com/2312781/83184210-1c46f500-a0f7-11ea-9d3f-b59115865435.png)

Is there a way to drop into pdb on error in visidata?

**Comment by anjakefala** [comment]
@jtf621 Can you copy paste the contents of `def save_sqlite` in `/home/jeremy/public-code/visidata/visidata/loaders/sqlite.py`?

**Comment by anjakefala** [comment]
> Is there a way to drop into pdb on error in visidata?

Sadly, no. =( But you can use vd.status() to print the contents of variables to status.

**Comment by jtf621** [comment]
@anjakefala how do I run vd.status() in visidata?

Here is the code
```
@VisiData.api
def save_sqlite(vd, p, *vsheets):
    import sqlite3
    conn = sqlite3.connect(str(p))
    c = conn.cursor()

    sqltypes = {
        int: 'INTEGER',
        float: 'REAL',
        currency: 'REAL'
    }

    for vs in vsheets:
        tblname = clean_to_id(vs.name)
        sqlcols = []
        for col in vs.visibleCols:
            sqlcols.append('"%s" %s' % (col.name, sqltypes.get(col.type, 'TEXT')))
        sql = 'CREATE TABLE IF NOT EXISTS "%s" (%s)' % (tblname, ', '.join(sqlcols))
        c.execute(sql)

        for r in Progress(vs.rows, 'saving'):
            sqlvals = []
            for col in vs.visibleCols:
                v = col.getTypedValue(r)
                if isinstance(v, TypedWrapper):
                    if isinstance(v, TypedExceptionWrapper):
                        v = options_safe_error
                    else:
                        v = None
                sqlvals.append(v)
            sql = 'INSERT INTO "%s" VALUES (%s)' % (tblname, ','.join('?' for v in sqlvals))
            c.execute(sql, sqlvals)

    conn.commit()

    status("%s save finished" % p)
```

**Comment by anjakefala** [comment]
For example! I would modify this block

```
        for r in Progress(vs.rows, 'saving'):
            sqlvals = []
            for col in vs.visibleCols:
                v = col.getTypedValue(r)
                if isinstance(v, TypedWrapper):
                    if isinstance(v, TypedExceptionWrapper):
                        v = options_safe_error
                    else:
                        v = None
                sqlvals.append(v)
            sql = 'INSERT INTO "%s" VALUES (%s)' % (tblname, ','.join('?' for v in sqlvals))
            c.execute(sql, sqlvals)
```

to be

```
        for r in Progress(vs.rows, 'saving'):
            sqlvals = []
            for col in vs.visibleCols:
                v = col.getTypedValue(r)
                if isinstance(v, TypedWrapper):
                    if isinstance(v, TypedExceptionWrapper):
                        v = options_safe_error
                    else:
                        v = None
                sqlvals.append(v)
            sql = 'INSERT INTO "%s" VALUES (%s)' % (tblname, ','.join('?' for v in sqlvals))
+          vd.status(sql)
+          vd.status(tuple(sqlvals))
            c.execute(sql, sqlvals)
```

It is super curious. There is my code change, and we are using the identical file. I wonder why I cannot reproduce the issue.

**Comment by anjakefala** [comment]
Thank you so much for helping out!

**Comment by jtf621** [comment]
@anjakefala I modified the code to print to a tmp file.  When I used `vd.status` the message was overwritten by the error log.  Is there a way to see all the messages from vd.status?  I tried adding a `pdb.set_trace` call but the debugging was muddled by the ui.

my code 
```
@VisiData.api
def save_sqlite(vd, p, *vsheets):
    import sqlite3
    conn = sqlite3.connect(str(p))
    c = conn.cursor()

    sqltypes = {
        int: 'INTEGER',
        float: 'REAL',
        currency: 'REAL'
    }

    for vs in vsheets:
        tblname = clean_to_id(vs.name)
        sqlcols = []
        for col in vs.visibleCols:
            sqlcols.append('"%s" %s' % (col.name, sqltypes.get(col.type, 'TEXT')))
        sql = 'CREATE TABLE IF NOT EXISTS "%s" (%s)' % (tblname, ', '.join(sqlcols))
        c.execute(sql)

        for r in Progress(vs.rows, 'saving'):
            sqlvals = []
            for col in vs.visibleCols:
                v = col.getTypedValue(r)
                if isinstance(v, TypedWrapper):
                    if isinstance(v, TypedExceptionWrapper):
                        v = options_safe_error
                    else:
                        v = None
                sqlvals.append(v)
            sql = 'INSERT INTO "%s" VALUES (%s)' % (tblname, ','.join('?' for v in sqlvals))
            
            with open('tmp.txt', 'w') as f:
                print(sql, file=f)
                print(tuple(map(repr, sqlvals)), file=f)
                
            c.execute(sql, sqlvals)

    conn.commit()

    status("%s save finished" % p)
```

The debug log is 

```
INSERT INTO "employees" VALUES (?,?,?,?,?)
("'employees.dept'", '4', '3', "'deptno'", 'employees')
```
The code seems to be trying to save the sheet that indexes all the tables (not sure what you call this sheet)

![image](https://user-images.githubusercontent.com/2312781/83353224-ff8d0600-a31e-11ea-8f7c-3df90dcdd7d5.png)

**Comment by anjakefala** [comment]
@jtf621 Awesome, that was the hinted I needed to be able to reproduce this. 

Okay, here is the confusion.

I was saving the new sqlite by selecting the tables I wanted to save in that IndexSheet, and then pressing `g Ctrl+S`. You were saving all of them, including the TableSheet, by using `g Ctrl+S` on an SqliteSheet.

It is confusing that the two variants behave differently. For now, as a workaround, you can:
* select the tables you want to save on the IndexSheet
* press `g Ctrl+S` on the IndexSheet to save the selected tables to an sqlite database

I am going to investigate why the IndexSheet is failing to save as a table. I am not sure if that will be fixable (yet), but we can at least cover this with documentation and give it a proper warning().

**Comment by anjakefala** [comment]
Pushed a fix! Thank you so much @jtf621 for sticking with this.
