### ISSUE TITLE
[help keystrokes] Help keystrokes has longnames for about 20 commands

### ISSUE THREAD

**Issue by frosencrantz** [saulpw/visidata#621]
**Small description**
Keystrokes in HelpSheet display commands not keystrokes for about 20 commands.

**Expected result**
Keystroke values

**Actual result with screenshot**

sheet	longname	keystrokes
TableSheet	go-next-selected	next-selected
TableSheet	go-prev-selected	prev-selected
TableSheet	setcol-clipboard	paste-cells
TableSheet	search-prev	prev-search
TableSheet	setcol-input	edit-cells
TableSheet	setcol-fill	fill-nulls
TableSheet	go-next-value	next-value
TableSheet	go-right-page	page-right
BaseSheet	jump-prev	prev-sheet
TableSheet	go-prev-value	prev-value
BaseSheet	open-new	add-sheet
TableSheet	go-next-null	next-null
TableSheet	go-left-page	page-left
TableSheet	go-prev-null	prev-null
TableSheet	open-row	dive-row
DirSheet	open-row	dive-row
BaseSheet	open-statuses	statuses
Canvas	zoomout-mouse	2097152
BaseSheet	show-status	status

**Steps to reproduce with sample data and a .vd**
Visit the help sheet, and look for the long commands above.

**Additional context**
Please include the version of VisiData. Latest from develop

**Comment by anjakefala** [comment]
I think this is a bug related to `alias()`.

Nice catch! I am going to see if it is fixable.

**Comment by anjakefala** [comment]
Fixed on `develop`!

**Comment by frosencrantz** [comment]
Awesome as always Anja!

**Comment by frosencrantz** [comment]
Hi @anjakefala  It is not clear if responding to closed bugs is ever seen.

If there is no response in a week, I'll open a new bug.

But this issue is still happening but only for the status commands.
   https://asciinema.org/a/exF54SsNFfmfxZFE4AmEQBviB

**Comment by anjakefala** [comment]
Ah, this is because they `status` and `statuses` do not contain `-`!

**Comment by anjakefala** [comment]
Should be fixed now!

**Comment by frosencrantz** [comment]
Thanks, @anjakefala!
